package example.grpc.server;

/* these are generated by the hello-world-server contract */
import example.grpc.TicTacToe;
import example.grpc.TicTacToeServiceGrpc;
import io.grpc.stub.StreamObserver;

public class TicTacToeServiceImpl extends TicTacToeServiceGrpc.TicTacToeServiceImplBase {

	private TTT ttt = new TTT();

	@Override
	public void play(TicTacToe.PlayRequest request, StreamObserver<TicTacToe.PlayResponse> responseObserver) {
		System.out.println(request);
		Boolean accepted = ttt.play(request.getRow(), request.getColumn(), request.getPlayer());
		TicTacToe.PlayResponse response = TicTacToe.PlayResponse.newBuilder().setAccepted(accepted).build();
		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void checkWinner(TicTacToe.CheckWinnerRequest request, StreamObserver<TicTacToe.CheckWinnerResponse> responseObserver) {
		System.out.println(request);
		TicTacToe.CheckWinnerResponse response = TicTacToe.CheckWinnerResponse.newBuilder().setPlayer(ttt.checkWinner()).build();
		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void currentBoard(TicTacToe.CurrentBoardRequest request, StreamObserver<TicTacToe.CurrentBoardResponse> responseObserver) {
		System.out.println(request);
		TicTacToe.CurrentBoardResponse response = TicTacToe.CurrentBoardResponse.newBuilder().setBoard(ttt.currentBoard()).build();
		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

}
