package example.grpc.client;

/* these are generated by the hello-world-server contract */
import example.grpc.TicTacToeServiceGrpc;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

public class TicTacToeClient {

	public static void main(String[] args) throws Exception {
		System.out.println(TicTacToeClient.class.getSimpleName());

		// receive and print arguments
		System.out.printf("Received %d arguments%n", args.length);
		for (int i = 0; i < args.length; i++) {
			System.out.printf("arg[%d] = %s%n", i, args[i]);
		}

		// check arguments
		if (args.length < 2) {
			System.err.println("Argument(s) missing!");
			System.err.printf("Usage: java %s host port%n", TicTacToeClient.class.getName());
			return;
		}

		final String host = args[0];
		final int port = Integer.parseInt(args[1]);
		final String target = host + ":" + port;

		// Channel is the abstraction to connect to a service endpoint
		// Let us use plaintext communication because we do not have certificates
		final ManagedChannel channel = ManagedChannelBuilder.forTarget(target).usePlaintext().build();

		TicTacToeServiceGrpc.TicTacToeServiceBlockingStub stub = TicTacToeServiceGrpc.newBlockingStub(channel);
		Game g = new Game(stub);
		g.playGame();
		g.congratulate();

		// A Channel should be shutdown before stopping the process.
		channel.shutdownNow();
	}

}
